---
abstract: 'Nagios plugin to check over the HTTP protocol.'
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Response: 0
  Test::MockObject: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nagios-Plugin-OverHTTP
no_index:
  directory:
    - inc
    - t
requires:
  Data::Validate::Domain: 0.02
  Data::Validate::URI: 0.05
  Getopt::Long::Descriptive: 0
  LWP::UserAgent: 0
  Moose: 0.74
  MooseX::Getopt: 0.18
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0.08
  Readonly: 0
  Scalar::Util: 1.19
  URI: 0
  perl: 5.8.1
  version: 0.74
resources:
  homepage: http://github.com/dougwilson/perl5-nagios-plugin-overhttp/tree/master
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dougwilson/perl5-nagios-plugin-overhttp.git
version: 0.07
